<?php

namespace AppBundle\Repository\Stadium;

use AppBundle\Entity\Stadium\BookedSeat;

/**
 * BookedSeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookedSeatRepository extends \Doctrine\ORM\EntityRepository
{
    const RESERVED = 'reserved';
    const IN_PROCESS = 'in_process';

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findInReserveProcessSeats()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('seat')
            ->from(BookedSeat::class, 'seat')
            ->where(
                $qb->expr()->eq('seat.isBooked', 0)
            )
        ;

        return $qb;
    }

    /**
     * @param string|null $q
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findByQ(string $q = null)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('seat')
            ->from(BookedSeat::class, 'seat')
        ;

        switch ($q) {
            case self::RESERVED:
                $qb
                    ->andWhere(
                        $qb->expr()->eq('seat.isBooked', 1)
                    );
                break;
            case self::IN_PROCESS:
                $qb
                    ->andWhere(
                        $qb->expr()->eq('seat.isBooked', 0)
                    );
                break;
        }

        return $qb;
    }
}
